//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inspecaoViaturasZas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class motorista
    {
        public int motorista_id { get; set; }
        public string nome { get; set; }
        public string contacto { get; set; }
        public int n_motorista { get; set; }
    }
}
