//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inspecao
    {
        public int inspecao_id { get; set; }
        public int viatura_id { get; set; }
        public Nullable<int> motorista_id { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public string chassis { get; set; }
        public string Eixo_Frente { get; set; }
        public string Eixo_Traz { get; set; }
        public string Motor { get; set; }
        public string Caixa_Velocidades { get; set; }
        public string Sistema_de_Ar { get; set; }
        public string Sistema_Eletrico { get; set; }
        public string Outros { get; set; }
    
        public virtual viatura viatura { get; set; }
    }
}
