//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class viatura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public viatura()
        {
            this.inspecao = new HashSet<inspecao>();
        }
    
        public int viatura_id { get; set; }
        public string matricula { get; set; }
        public string movel { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public Nullable<int> capacidade { get; set; }
        public Nullable<int> peso_bruto { get; set; }
        public Nullable<int> Tara { get; set; }
        public Nullable<bool> Oficina { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inspecao> inspecao { get; set; }
    }
}
